FROM python:3.10-slim-buster
#to send python error messages to terminal(any data send to terminal will be displayed in the terminal)
ENV PYTHONUNBUFFERED=1
WORKDIR /django
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt




